"""empty message

Revision ID: c32aab99a7c7
Revises: 7d9dc6233434
Create Date: 2024-12-23 11:47:12.208771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32aab99a7c7'
down_revision = '7d9dc6233434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('data_compra',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('data_compra',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
